adding separate workflows for static analysis

diff --git a/.github/workflows/pyflakes.yml b/.github/workflows/pyflakes.yml
--- a/.github/workflows/pyflakes.yml
+++ b/.github/workflows/pyflakes.yml
@@ -1,4 +1,4 @@
-name: Autopep static analysis
+name: Pyflakes static analysis
 
 on: [push]
 
@@ -16,7 +16,7 @@ jobs:
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
-        pip install autopep8
-    - name: Autopep8 format analysis 
+        pip install pyflakes
+    - name: Pyflakes static analysis
       run: |
-        find /path/to/directory -type f -name '*.py' | xargs -I {} sh -c 'autopep8 --diff "{}" | grep -q . && echo "{}: Failed" || echo "{}: Passed"'
+        find /path/to/directory -type f -name '*.py' | xargs -I {} sh -c 'pyflakes "{}" | grep -q . && echo "{}: Failed" || echo "{}: Passed"'
